###

POST http://127.0.0.1:8080/api/v1/login HTTP/1.1
Content-Type: application/json

{ 
    "email":"jjag@gmail.com", 
    "password":"1234" 
}

###

GET http://localhost:8080/api/v1/person HTTP/1.1
Content-Type: application/json


###

POST http://localhost:8080/api/v1/register HTTP/1.1
Content-Type: application/json

{ 
    "userName":"juan",
    "email":"jjag@gmail.com", 
    "password":"1234",
    "passwordConfirm":"1234",
    "userType":"cli" 
}

###

GET http://localhost:8080/api/v1/servicios HTTP/1.1
Content-Type: application/json

###

PUT  http://localhost:8080/api/v1/updateRegister HTTP/1.1
Content-Type: application/json

{ 
    "name":"",
    "lastName":"", 
    "phone":"",
    "dni":"",
    "direccion":"",
    "calle":"Liniers",
    "numero":"1779", 
    "cPostal":"7000",
    "nameCiudad":"",
    "namePais":"" 
}

###

PUT  http://localhost:8080/api/v1/platos/Milas HTTP/1.1
Content-Type: application/json

{
    "name": "Milas",
    "value": 700,
    "ingredients": "Carne de Ternera"
}